# Generated by Django 5.1 on 2024-09-04 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_prices', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField()),
                ('start_month', models.CharField(choices=[('Farvardin', 'Farvardin'), ('Ordibehesht', 'Ordibehesht'), ('Khordad', 'Khordad'), ('Tir', 'Tir'), ('Mordad', 'Mordad'), ('Shahrivar', 'Shahrivar'), ('Mehr', 'Mehr'), ('Aban', 'Aban'), ('Azar', 'Azar'), ('Dey', 'Dey'), ('Bahman', 'Bahman'), ('Esfand', 'Esfand')], max_length=20)),
                ('end_month', models.CharField(choices=[('Farvardin', 'Farvardin'), ('Ordibehesht', 'Ordibehesht'), ('Khordad', 'Khordad'), ('Tir', 'Tir'), ('Mordad', 'Mordad'), ('Shahrivar', 'Shahrivar'), ('Mehr', 'Mehr'), ('Aban', 'Aban'), ('Azar', 'Azar'), ('Dey', 'Dey'), ('Bahman', 'Bahman'), ('Esfand', 'Esfand')], max_length=20)),
                ('assets', models.ManyToManyField(related_name='sandoghs', to='bazar.asset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
