# Generated by Django 5.1 on 2024-09-03 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField()),
                ('start_month', models.CharField(choices=[('Farvardin', 'Farvardin'), ('Ordibehesht', 'Ordibehesht'), ('Khordad', 'Khordad'), ('Tir', 'Tir'), ('Mordad', 'Mordad'), ('Shahrivar', 'Shahrivar'), ('Mehr', 'Mehr'), ('Aban', 'Aban'), ('Azar', 'Azar'), ('Dey', 'Dey'), ('Bahman', 'Bahman'), ('Esfand', 'Esfand')], max_length=20)),
                ('end_month', models.CharField(choices=[('Farvardin', 'Farvardin'), ('Ordibehesht', 'Ordibehesht'), ('Khordad', 'Khordad'), ('Tir', 'Tir'), ('Mordad', 'Mordad'), ('Shahrivar', 'Shahrivar'), ('Mehr', 'Mehr'), ('Aban', 'Aban'), ('Azar', 'Azar'), ('Dey', 'Dey'), ('Bahman', 'Bahman'), ('Esfand', 'Esfand')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.sandogh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
